/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FhirtStopWatch {
        "hours": string;
        "hundredthSeconds": string;
        "minutes": string;
        "seconds": string;
    }
    interface FhirtStopWatchBox {
        "updateInterval": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFhirtStopWatchElement extends Components.FhirtStopWatch, HTMLStencilElement {
    }
    var HTMLFhirtStopWatchElement: {
        prototype: HTMLFhirtStopWatchElement;
        new (): HTMLFhirtStopWatchElement;
    };
    interface HTMLFhirtStopWatchBoxElement extends Components.FhirtStopWatchBox, HTMLStencilElement {
    }
    var HTMLFhirtStopWatchBoxElement: {
        prototype: HTMLFhirtStopWatchBoxElement;
        new (): HTMLFhirtStopWatchBoxElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fhirt-stop-watch": HTMLFhirtStopWatchElement;
        "fhirt-stop-watch-box": HTMLFhirtStopWatchBoxElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FhirtStopWatch {
        "hours"?: string;
        "hundredthSeconds"?: string;
        "minutes"?: string;
        "seconds"?: string;
    }
    interface FhirtStopWatchBox {
        "updateInterval"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fhirt-stop-watch": FhirtStopWatch;
        "fhirt-stop-watch-box": FhirtStopWatchBox;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fhirt-stop-watch": LocalJSX.FhirtStopWatch & JSXBase.HTMLAttributes<HTMLFhirtStopWatchElement>;
            "fhirt-stop-watch-box": LocalJSX.FhirtStopWatchBox & JSXBase.HTMLAttributes<HTMLFhirtStopWatchBoxElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
