/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FhirtStopWatch {
        "hours": string;
        "hundredthSeconds": string;
        "minutes": string;
        "seconds": string;
    }
    interface FhirtStopWatchBox {
    }
}
declare global {
    interface HTMLFhirtStopWatchElement extends Components.FhirtStopWatch, HTMLStencilElement {
    }
    var HTMLFhirtStopWatchElement: {
        prototype: HTMLFhirtStopWatchElement;
        new (): HTMLFhirtStopWatchElement;
    };
    interface HTMLFhirtStopWatchBoxElement extends Components.FhirtStopWatchBox, HTMLStencilElement {
    }
    var HTMLFhirtStopWatchBoxElement: {
        prototype: HTMLFhirtStopWatchBoxElement;
        new (): HTMLFhirtStopWatchBoxElement;
    };
    interface HTMLElementTagNameMap {
        "fhirt-stop-watch": HTMLFhirtStopWatchElement;
        "fhirt-stop-watch-box": HTMLFhirtStopWatchBoxElement;
    }
}
declare namespace LocalJSX {
    interface FhirtStopWatch {
        "hours"?: string;
        "hundredthSeconds"?: string;
        "minutes"?: string;
        "seconds"?: string;
    }
    interface FhirtStopWatchBox {
    }
    interface IntrinsicElements {
        "fhirt-stop-watch": FhirtStopWatch;
        "fhirt-stop-watch-box": FhirtStopWatchBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fhirt-stop-watch": LocalJSX.FhirtStopWatch & JSXBase.HTMLAttributes<HTMLFhirtStopWatchElement>;
            "fhirt-stop-watch-box": LocalJSX.FhirtStopWatchBox & JSXBase.HTMLAttributes<HTMLFhirtStopWatchBoxElement>;
        }
    }
}
